### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by kpchoy** [kpchoy/HypeCamp#2]
- [ ] User can sign up, login, logout
- [ ] User can demo login on site
- [ ] Styling

**Comment by andywynkoop** [comment]
Hey Kevin,
Everything for user auth is looking great so far! Here are a few changes to make:
- [ ] Remove redux logger and all console logs from production
- [ ] Based on the message I get in the console, it looks like the buttons to navigate between sign up and log in are nested inside of a form, they should probably be moved into their own element so they don't trigger form submission
- [x] Logo should be clickable and redirect to `/`
- [x] Start hosting button should probably do something, maybe open the sign up modal?
- [x] Need working demo login
- [x] If I visit a random route, `/ssdfsadfsadsadfgvr/`, I should get either a 404 page or be redirected back to `/`
- [ ] Errors should clear when going between sign up and log in pages
- [ ] Errors should also clear when I close and re-open the modal
- [x] Start hosting, log in, and sign up should have `cursor: pointer` on hover

**Comment by kpchoy** [comment]
Hey andy when you ahve time can you help me with the last parts of my user auth, thanks

**Comment by andywynkoop** [comment]
👍
